### ISSUE TITLE
Parse GSA line

### ISSUE THREAD

**Issue by DemetriouJohn** [DevsAnon/NmeaParser#6]
$GPGSA,A,3,04,05,,09,12,,,24,,,,,2.5,1.3,2.1*39

Where:
     GSA      Satellite status
     A        Auto selection of 2D or 3D fix (M = manual) 
     3        3D fix - values include: 1 = no fix
                                       2 = 2D fix
                                       3 = 3D fix
     04,05... PRNs of satellites used for fix (space for 12) 
     2.5      PDOP (dilution of precision) 
     1.3      Horizontal dilution of precision (HDOP) 
     2.1      Vertical dilution of precision (VDOP)
     *39      the checksum data, always begins with *

**Comment by helluvamatt** [comment]
I'm interested in helping with this. I'm expecting a USB GPS device to be delivered tomorrow (4/22/2021) and I'd like to assist with some of the messages that aren't yet supported.

For the GSA message, it was reported that some devices include an additional field after the VDOP and before the checksum that is the SystemID. More details: https://gpsd.gitlab.io/gpsd/NMEA.html#_gsa_gps_dop_and_active_satellites

**Comment by DemetriouJohn** [comment]
Feel free to open a Pull request for this, or wait until I implement it. Either way is fine by me.
Released versions live under 
https://www.nuget.org/packages/NmeaParser/
